### ISSUE TITLE
which does what??? No readme, no description, nothing

### ISSUE THREAD

**Issue by abada** [collinprice/ca.intentextension#1]

**Comment by collinprice** [comment]
I ran out of time yesterday to write the documentation. This module only exists until [this](https://github.com/appcelerator/titanium_mobile/pull/7073) pull request is accepted. For now there is [example](https://github.com/collinprice/ca.intentextension/blob/master/android/example/app.js) code. It wraps a Titanium Intent with a subclass that allows you to pass Intents and Bitmaps as parameters to `putExtra`.

**Comment by abada** [comment]
Thank you :+1:
